#!/bin/sh
echo `date` $@ >> /tmp/update3g.log

if [ $# -ne 3 -o -z "$1" -o -z "$2" -o -z "$3" ]; then
    echo "usage: $0 action target device"
    exit
fi

TARGET=$2
DEVICE_MARKER=/tmp/3g-modem.device.${TARGET}

PIN_FILE=/etc/modem.pin

if [ -r ${PIN_FILE} -a -f ${PIN_FILE} ]; then
    PIN=`cat ${PIN_FILE}`
else
    PIN="0000"
fi

# function to update wvdial.conf

WVDIAL_CONF=/etc/wvdial.conf
REG_WVDIAL_1="s/\(^Modem\s=\s\/dev\/\).*/\1$3/g"
REG_WVDIAL_2="s/\(^Init9\s=\s\AT+CPIN=\).*/\1${PIN}/g"

update_wvdial() {
    # update wvdial.conf
    sed ${REG_WVDIAL_1} ${WVDIAL_CONF} | sed ${REG_WVDIAL_2} > ${WVDIAL_CONF}.$$
    mv -f ${WVDIAL_CONF}.$$ ${WVDIAL_CONF}
}

# function to update gnokiirc

GNOKII_CONF=/etc/gnokiirc
REG_GNOKII="s/\(^port\s=\s\/dev\/\).*/\1$3/g"

update_gnokii() {
    sed ${REG_GNOKII} ${GNOKII_CONF} > ${GNOKII_CONF}.$1
    #mv -f ${GNOKII_CONF}.$$ ${GNOKII_CONF}
}

case "$1" in

    add)
	if [ "$2" = "wvdial" ]; then
	    update_wvdial

	    # unlock SIM by dialing unlock if PIN file exists
            if [ -f $PIN_FILE ]; then
                wvdial unlock
            fi

	    echo $3 > ${DEVICE_MARKER}

	elif [ "$2" = "gnokii" ]; then
	    # generate device specific gnokiirc
	    update_gnokii $3

            # run gnokii --identify in background
            rm -f /tmp/usb_modem.$3.$$
            gnokii --config ${GNOKII_CONF}.$3 --identify | grep IMEI | awk '{print $3}' > /tmp/usb_modem.$3.$$ 2>/dev/null &
            PID=$!

            # wait 5 seconds
            sleep 5

            # check if port is active
            if [ -s /tmp/usb_modem.$3.$$ ]; then

                mv -f ${GNOKII_CONF}.$3 ${GNOKII_CONF}

		echo $3 > ${DEVICE_MARKER}

		# retrieve IMEI
		IMEI=`cat /tmp/usb_modem.$3.$$`

                # emit 'roundrock-3g-modem-added' event to start smsd
                initctl emit --no-wait roundrock-3g-modem-added IMEI=$IMEI
            fi

            kill $PID >/dev/null 2>&1

            rm -f /tmp/usb_modem.$3.$$ ${GNOKII_CONF}.$3
	fi
    ;;

    remove)
	/bin/rm -f ${DEVICE_MARKER}

	if [ "$2" = "gnokii" ]; then
	    # emit 'roundrock-3g-modem-removed' event to stop smsd
	    initctl emit --no-wait roundrock-3g-modem-removed
	fi
    ;;
esac
