#!/bin/sh
#

# note xinit needs full server path
XSERVER=/usr/bin/Xorg
if [ -f /usr/bin/Xfbdev ]; then
  XSERVER=/usr/bin/Xfbdev
fi
if [ -f /usr/bin/Xorg ]; then
  XSERVER=/usr/bin/Xorg
fi

export USER=root

ARGS=" -nolisten tcp -br vt7 "

. /etc/profile

DISPLAY=':0'

exec xinit /etc/X11/Xsession -- $XSERVER $DISPLAY $ARGS >/var/log/x.log 2>&1
