CREATE TABLE "sync_remote_machines" ("id" INTEGER PRIMARY KEY NOT NULL, "machine_id" varchar(36) NOT NULL, "last_synced" int DEFAULT -1);
CREATE TABLE "syncs" ("id" INTEGER PRIMARY KEY NOT NULL ,"crud" varchar(255) NOT NULL ,"machine_id" varchar(36) ,"from_machine_id" varchar(36) ,"method_id" varchar(36) NOT NULL ,"method_type" varchar(45) NOT NULL ,"method_table" varchar(45) NOT NULL ,"created" INTEGER NOT NULL ,"modified" INTEGER NOT NULL);
CREATE TABLE "table_bookings" ("id" VARCHAR,"table_id" VARCHAR,"booking" INTEGER,"contact" VARCHAR,"telephone" VARCHAR,"address" VARCHAR,"note" VARCHAR,"party_size" INTEGER, "created" INTEGER);
CREATE TABLE "table_marks" ("id" VARCHAR PRIMARY KEY  NOT NULL , "name" VARCHAR, "period" INTEGER,"opdeny" BOOL DEFAULT 0);
CREATE TABLE "table_order_locks" ("id" VARCHAR NOT NULL , "machine_id" VARCHAR NOT NULL , "machine_addr" VARCHAR, "created" INTEGER, "modified" INTEGER, PRIMARY KEY ("id"));
CREATE TABLE "table_orders" ("id" VARCHAR,"total" FLOAT,"table_no" INTEGER,"check_no" INTEGER,"service_clerk" VARCHAR,"sequence" VARCHAR,"no_of_customers" INTEGER,"transaction_created" INTEGER,"created" INTEGER,"modified" INTEGER,"status" INTEGER,"terminal_no" VARCHAR, "table_id" VARCHAR);
CREATE TABLE "table_regions" ("id" VARCHAR, "name" VARCHAR, "image" VARCHAR);
CREATE TABLE "table_settings" ("id" CHAR PRIMARY KEY  NOT NULL , "value" CHAR NOT NULL );
CREATE TABLE "table_statuses" ("id" VARCHAR,"table_id" VARCHAR,"table_no" INTEGER,"created" INTEGER,"modified" DOUBLE,"hostby" INTEGER,"start_time" INTEGER,"end_time" INTEGER,"status" INTEGER,"mark" VARCHAR,"mark_op_deny" BOOL,"mark_user" VARCHAR, "order_count" INTEGER DEFAULT 0, "sum_customer" INTEGER DEFAULT 0, "sum_total" FLOAT DEFAULT 0);
CREATE TABLE "table_wait_lists" ("id" VARCHAR PRIMARY KEY  NOT NULL , "name" VARCHAR NOT NULL , "arrive_time" INTEGER, "no_of_customers" INTEGER, "partial" BOOL, "created" INTEGER, "modified" INTEGER);
CREATE TABLE "tables" ("id" VARCHAR PRIMARY KEY NOT NULL,"table_no" INTEGER,"table_name" VARCHAR,"table_region_id" VARCHAR,"seats" INTEGER,"active" BOOL,"tag" VARCHAR,"destination" VARCHAR,"minimum_charge_per_table" FLOAT,"minimum_charge_per_guest" FLOAT,"styles" VARCHAR);
CREATE UNIQUE INDEX "sync_remote_machines_machine_id" on "sync_remote_machines" ("machine_id");
CREATE INDEX "syncs_from_machine_id" on "syncs" ("from_machine_id");
CREATE INDEX "table_bookings_booking" ON "table_bookings" ("booking" ASC);
CREATE INDEX "table_bookings_table_id" ON "table_bookings" ("table_id" ASC);
CREATE INDEX "table_order_locks_machine_id" on "table_order_locks" ("machine_id");
CREATE INDEX "table_orders_table_id_tc" on "table_orders" ("table_id", "transaction_created");
CREATE INDEX "table_statuses_modified" on "table_statuses" ("modified");
CREATE INDEX "table_statuses_status" on "table_statuses" ("status");
CREATE INDEX "table_statuses_table_id" on "table_statuses" ("table_id");
