content viviecr content/ xpcnativewrappers=yes

overlay chrome://vivipos/content/mainUIOverlay.xul chrome://viviecr/content/overlay.xul

skin viviecr classic-800x600/1.0 skin/classic-800x600/
skin viviecr classic-1024x768/1.0 skin/classic-1024x768/
skin viviecr traditional-800x600/1.0 skin/traditional-800x600/
skin viviecr traditional-1024x768/1.0 skin/traditional-1024x768/

locale viviecr en locale/en/


