#!/usr/bin/env /bin/sh

#
# vivipos launcher
# 
. /etc/environment

#set -x
RETVAL=127;
DIR=`dirname $0`
DATABASE=/data/databases
SQLITE3=/usr/bin/sqlite3

# set X11 DISPLAY if zero
if [ -z "$DISPLAY" ]; then
  export DISPLAY=:0
fi

#
# include l10n messages
#
if [ -x /data/scripts/l10n_messages ]; then
    . /data/scripts/l10n_messages
fi
MSG_RUN_VIVIPOS_STARTING=${MSG_RUN_VIVIPOS_STARTING:-"Starting VIVIPOS ......"}
MSG_RUN_VIVIPOS_INTEGRITY_CHECK=${MSG_RUN_VIVIPOS_INTEGRITY_CHECK:-"Integrity Check:"}
MSG_RUN_VIVIPOS_REBUILDING=${MSG_RUN_VIVIPOS_REBUILDING:-"Rebuilding:"}


#
# do sqlite vacuum 
#
do_vacuum()
{

    for i in $DATABASE/*.sqlite; do
        echo "VACUUM;" | $SQLITE3 $i ;
    done

    chmod -R 775 $DATABASE ;
}

#
# start application
#
run()
{
    echo "`date +"%Y-%m-%d %H:%M:%S"` : Starting VIVIPOS FROM [run_vivipos]" >> ${DIR}/log/vivipos.log

    echo "`date +"%Y-%m-%d %H:%M:%S"` :   executing xulrunner [${DIR}/application.ini]" $@ >> ${DIR}/log/vivipos.log

    echo  "$MSG_RUN_VIVIPOS_STARTING" | \
    /usr/bin/aosd_cat -x 100 -n "Droid Serif 24" -u 800000 &

    # set env of system info
    eval `${DIR}/getSystemLicenseStub -v|awk -F"=" '$1 ~ /[A-Za-z0-9_]+/ { print "export " $1 "=\"" $2 "\"";  }'`
    ${DIR}/xulrunner/xulrunner ${DIR}/application.ini $@
    RETVAL=$?

    echo "`date +"%Y-%m-%d %H:%M:%S"` : Exit VIVIPOS [${RETVAL}]" >> ${DIR}/log/vivipos.log

    return ${RETVAL}
}


#
# reboot
#
reboot()
{
    # reboot machine if not in level [016]
    RUNLEVEL=`/sbin/runlevel | awk '{print $2}' | sed 's/[016]//g'`
    if [ -n "${RUNLEVEL}" ]; then
        exec /sbin/reboot
    fi
}

run || reboot
