#!/usr/bin/env /bin/sh

#
# vivipos launcher
# 
. /etc/environment

#set -x
RETVAL=127;
DIR=`dirname $0`
DATABASE=/data/databases
SQLITE3=/usr/bin/sqlite3

# set X11 DISPLAY if zero
if [ -z "$DISPLAY" ]; then
  export DISPLAY=:0
fi

#
# include l10n messages
#
if [ -x /data/scripts/l10n_messages ]; then
    . /data/scripts/l10n_messages
fi
MSG_RUN_VIVIPOS_STARTING=${MSG_RUN_VIVIPOS_STARTING:-"Starting VIVIPOS ......"}
MSG_RUN_VIVIPOS_INTEGRITY_CHECK=${MSG_RUN_VIVIPOS_INTEGRITY_CHECK:-"Integrity Check:"}
MSG_RUN_VIVIPOS_REBUILDING=${MSG_RUN_VIVIPOS_REBUILDING:-"Rebuilding:"}


#
# do sqlite vacuum 
#
do_vacuum()
{

    for i in $DATABASE/*.sqlite; do
        echo "VACUUM;" | $SQLITE3 $i ;
    done

    chmod -R 775 $DATABASE ;
}


#
# do sqlite integrity check
#
do_integrity_check()
{

    for i in $DATABASE/*.sqlite; do
                dbname=`basename $i`
                /usr/bin/aosd_cat -F "Sans 20"  -x 100 -y -120 -d 600000 "${MSG_RUN_VIVIPOS_INTEGRITY_CHECK} ${dbname}" &
                echo "`date +"%Y-%m-%d %H:%M:%S"` :   integrity_check [${dbname}]" >> ${DIR}/log/vivipos.log

		result=`$SQLITE3 $i "PRAGMA integrity_check"`
                pkill aosd_cat
		if [ "$?" = "0" ] && [ ! -z "$result" ] && [ "$result" != "ok" ]; then
                    /usr/bin/aosd_cat -F "Sans 20" -x 100 -y -80 -d 600000 "${MSG_RUN_VIVIPOS_REBUILDING} ${dbname}" &
                    echo "`date +"%Y-%m-%d %H:%M:%S"` :   rebuilding [${dbname}]" >> ${DIR}/log/vivipos.log

                    $SQLITE3 $i ".dump" | $SQLITE3 $i.tmp
                    cp $i.tmp $i
                    rm -f $i.tmp
                    pkill aosd_cat
		fi
    done

}

#
# do disk usage check
#
do_disk_usage_check()
{
	if [ -x /data/scripts/diskspace_usage.sh ]; then
		/data/scripts/diskspace_usage.sh
	fi
}


# for loop runing vivipos forever
while [ $RETVAL != 0 ]; do

    echo "`date +"%Y-%m-%d %H:%M:%S"` : Starting VIVIPOS FROM [run_vivipos]" >> ${DIR}/log/vivipos.log

    # do_vacuum

	# do_integrity_check
	do_integrity_check

	do_disk_usage_check

    echo "`date +"%Y-%m-%d %H:%M:%S"` :   executing xulrunner [${DIR}/application.ini]" >> ${DIR}/log/vivipos.log

    /usr/bin/aosd_cat -x 100 -F "Sans 24" -d 800000  "$MSG_RUN_VIVIPOS_STARTING" &

	# set env of system info
	eval `${DIR}/getSystemLicenseStub -v|awk -F"=" '$1 ~ /[A-Za-z0-9_]+/ { print "export " $1 "=\"" $2 "\"";  }'`
	${DIR}/xulrunner/xulrunner ${DIR}/application.ini
    RETVAL=$?

    echo "`date +"%Y-%m-%d %H:%M:%S"` : Exit VIVIPOS [${RETVAL}]" >> ${DIR}/log/vivipos.log

done

