#!/bin/sh

#
# vivipos launcher
# 
. /etc/environment

RETVAL=127;
DIR=`dirname $0`
DATABASE=/data/databases
SQLITE3=/usr/bin/sqlite3
export DISPLAY=:0

#
# do sqlite vacuum 
#
do_vacuum()
{

    for i in $DATABASE/*.sqlite; do
        echo "VACUUM;" | $SQLITE3 $i ;
    done

    chmod -R 775 $DATABASE ;
}


#
# do sqlite integrity check
#
do_integrity_check()
{

    for i in $DATABASE/*.sqlite; do
                dbname=`basename $i`
                /usr/bin/aosd_cat -F "Sans 20"  -y -120 -d 600000 "integrity check (${dbname})..." &
                echo "`date +"%Y-%m-%d %H:%M:%S"` :   integrity_check [${dbname}]" >> ${DIR}/log/vivipos.log

		result=`$SQLITE3 $i "PRAGMA integrity_check"`
                pkill aosd_cat
		if [ "$result" != "ok" ]; then
                    /usr/bin/aosd_cat -F "Sans 20"  -y -80 -d 600000 "Rebuilding (${dbname})..." &
                    echo "`date +"%Y-%m-%d %H:%M:%S"` :   rebuilding [${dbname}]" >> ${DIR}/log/vivipos.log

                    $SQLITE3 $i ".dump" | $SQLITE3 $i.tmp
                    cp $i.tmp $i
                    rm -f $i.tmp
                    pkill aosd_cat
		fi
    done

}

#
# do disk usage check
#
do_disk_usage_check()
{
	if [ -x /data/scripts/diskspace_usage.sh ]; then
		/data/scripts/diskspace_usage.sh
	fi
}


# for loop runing vivipos forever
while [ $RETVAL != 0 ]; do

    echo "`date +"%Y-%m-%d %H:%M:%S"` : Starting VIVIPOS FROM [run_vivipos]" >> ${DIR}/log/vivipos.log

    # do_vacuum

	# do_integrity_check
	do_integrity_check

	do_disk_usage_check

    echo "`date +"%Y-%m-%d %H:%M:%S"` :   executing xulrunner [${DIR}/application.ini]" >> ${DIR}/log/vivipos.log

    /usr/bin/aosd_cat -F "Sans 24" -y -320 -d 800000  "Starting VIVIPOS ......" &
    ${DIR}/xulrunner/xulrunner ${DIR}/application.ini
    RETVAL=$?

    echo "`date +"%Y-%m-%d %H:%M:%S"` : Exit VIVIPOS [${RETVAL}]" >> ${DIR}/log/vivipos.log

done

