#!/bin/sh
#

#
# execute php sync client
#
cmd=${1:-help}
pid=$$
dir=`dirname $0`

cd $dir ;

#echo "pid = ${pid}"

find ${dir}/app/tmp -type f -exec rm -f {} \;

exec ${dir}/cake/console/cake -app ${dir}/app sync_client ${cmd}

