#!/bin/sh -x

DIR=`dirname $0`
ROOTFS=/home/vivipos/diskimage/rootfs

tar chp --owner=root -C $DIR/os/etc . | tar x --owner=root -C $ROOTFS/etc

tar c --owner=root -h -C $DIR/os/scripts . | tar x --owner=root -C $ROOTFS/sbin

tar c --owner=root -C $DIR/os/initramfs-tools . | tar x --owner=root -C $ROOTFS/usr/share/initramfs-tools

tar c --owner=root -C $DIR/os/profile . | tar x --owner=root -C $ROOTFS/data/profile

cp os/xpcom_ospasswd/*.xpt os/xpcom_ospasswd/*.so $ROOTFS/data/vivipos_sdk/components/
