#!/usr/bin/env /bin/sh
#
# vivipos launcher
# 
. /etc/environment

#set -x
RETVAL=127;
DIR=`dirname $0`

# set X11 DISPLAY if zero
if [ -z "$DISPLAY" ]; then
  export DISPLAY=:0
fi

echo "`date +"%Y-%m-%d %H:%M:%S"` : Starting VIVIPOS FROM [vivipos]" >> ${DIR}/log/vivipos.log
echo "`date +"%Y-%m-%d %H:%M:%S"` :   executing xulrunner [${DIR}/application.ini] $@" >> ${DIR}/log/vivipos.log

# set env of system info
eval `${DIR}/getSystemLicenseStub -v 2>/dev/null |awk -F"=" '$1 ~ /[A-Za-z0-9_]+/ { print "export " $1 "=\"" $2 "\"";  }'`
${DIR}/xulrunner/xulrunner ${DIR}/application.ini $@
RETVAL=$?

echo "`date +"%Y-%m-%d %H:%M:%S"` : Exit VIVIPOS [${RETVAL}]" >> ${DIR}/log/vivipos.log


exit $RETVAL

