#!/bin/sh
APP_DIR=`dirname $0`/../../;
SDK_DIR="$APP_DIR../../vivipos_sdk";

#flag=
#if [ -f messages.pot ]; then
#   flag=-j
#fi

xgettext -o messages.po --no-location --omit-header --msgid-bugs-address=irving.hsu@firich.com.tw -Lpython -k_ $APP_DIR/content/*.js $APP_DIR/content/controllers/*.js $SDK_DIR/chrome/content/bindings/*.xbl  $APP_DIR/content/helpers/*.js $APP_DIR/content/bindings/*.xbl $APP_DIR/content/reports/controllers/*.js $APP_DIR/content/reports/controllers/components/*.js $APP_DIR/content/reports/tpl/*/*.tpl

#combine pot and po to properties and append default msgstr
msgcat messages.pot messages.po -o messages.properties.po
rm messages.po

