#!/bin/sh
APP_DIR=`dirname $0`/../../;
#SDK_DIR="$APP_DIR../../vivipos_sdk";

#
# special treatment for defaults/preferences/your_order_report.js
#
grep -e "vivipos.fec.report.yourorder.field.[^.]*.name\"" $APP_DIR/defaults/preferences/your_order_report.js  > /tmp/your_order_report.js

xgettext -o messages1.po --from-code UTF-8 --msgid-bugs-address=irving.hsu@firich.com.tw -Lpython -k_:1 $APP_DIR/content/*.js $APP_DIR/content/controllers/*.js $APP_DIR/content/controllers/*/*.js $APP_DIR/content/helpers/*.js $APP_DIR/content/bindings/*.xbl $APP_DIR/content/reports/controllers/*.js $APP_DIR/content/reports/controllers/components/*.js $APP_DIR/content/reports/tpl/*/*.tpl $APP_DIR/content/tpl/*.* $APP_DIR/content/promotions/*.js $APP_DIR/content/promotions/controllers/*.js $APP_DIR/content/promotions/triggers/*.js $APP_DIR/content/promotions/types/*.js

sed 's/charset=CHARSET/charset=UTF-8/g' messages1.po > messages.po

xgettext -j -o messages.po --from-code UTF-8 --omit-header --msgid-bugs-address=vivipos@firich.com.tw -Lpython -kpref:2 /tmp/your_order_report.js

#combine pot and po to properties and append default msgstr
msgcat messages.pot messages.po -o messages.properties.po
rm messages.po messages1.po

