# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1229509705);
user_pref("app.update.lastUpdateTime.background-update-timer", 1232081896);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1232082496);
user_pref("browser.places.importDefaults", false);
user_pref("extensions.enabledItems", "inspector@mozilla.org:2.0.0,{f13b157f-b174-47e7-a34d-4815ddfdfeb8}:0.9.87.4,SQLiteManager@mrinalkant.blogspot.com:0.3.17,viviecr@firich.com.tw:0.1,langpack-zh-CN@firich.com.tw:0.1");
user_pref("extensions.newAddons", "langpack-zh-CN@firich.com.tw");
user_pref("extensions.sqlitemanager.mruPath.1", "/data/databases/vivipos.sqlite,/data/databases/vivipos_order.sqlite,/var/tmp/vivipos_order.sqlite,/var/tmp/vivipos.sqlite,/var/tmp/vivipos_acl.sqlite,");
user_pref("extensions.sqlitemanager.promptForLastDb", false);
user_pref("extensions.update.notifyUser", false);
user_pref("vivipos.fec.settings.AgeVerificationAck", false);
user_pref("vivipos.fec.settings.AllowOverStock", false);
user_pref("vivipos.fec.settings.Currencies", "[{\"currency\":\"NT\",\"currency_symbol\":\"NT\"},{\"currency\":\"USD\",\"currency_symbol\":\"$\",\"currency_exchange\":\"33.25\"},{\"currency\":\"\",\"currency_symbol\":\"\",\"currency_exchange\":\"\"},{\"currency\":\"\",\"currency_symbol\":\"\",\"currency_exchange\":\"\"},{\"currency\":\"\",\"currency_symbol\":\"\",\"currency_exchange\":\"\"},{\"currency\":\"\",\"currency_symbol\":\"\",\"currency_exchange\":\"\"}]");
user_pref("vivipos.fec.settings.DefaultTaxStatus", "ada388bd-545b-4d91-9fea-13e3bde73d07");
user_pref("vivipos.fec.settings.DefaultUser", "8a4d088b-8159-453c-b404-1baaa3aaa6f1");
user_pref("vivipos.fec.settings.DepartmentCols", 3);
user_pref("vivipos.fec.settings.DepartmentRows", 3);
user_pref("vivipos.fec.settings.FunctionPanelOnTop", false);
user_pref("vivipos.fec.settings.HideFPScrollbar", false);
user_pref("vivipos.fec.settings.HideNumPad", false);
user_pref("vivipos.fec.settings.PluCols", 3);
user_pref("vivipos.fec.settings.PluFilters", "%5B%5D");
user_pref("vivipos.fec.settings.PluRows", 5);
user_pref("vivipos.fec.settings.PositivePriceRequired", true);
user_pref("vivipos.fec.settings.PrecisionPrices", 2);
user_pref("vivipos.fec.settings.PrecisionTaxes", 2);
user_pref("vivipos.fec.settings.PriceLevelSchedule", "[{\"time\":\"00:00\",\"pricelevel\":0}]");
user_pref("vivipos.fec.settings.RegisterAtLeft", false);
user_pref("vivipos.fec.settings.TerminalID", "總統");
user_pref("vivipos.fec.settings.beepOnDiscountSurcharge", true);
user_pref("vivipos.fec.settings.beepOnItemAdd", true);
user_pref("vivipos.fec.settings.beepOnModify", true);
user_pref("vivipos.fec.settings.beepOnPayment", true);
user_pref("vivipos.fec.settings.beepOnScanningError", true);
user_pref("vivipos.fec.settings.beepOnSubtotal", true);
user_pref("vivipos.fec.settings.beepOnVOID", true);
user_pref("vivipos.fec.settings.device.mount.path", "/home/user/downloads/data/");
user_pref("vivipos.fec.settings.functionpanel.columns", 3);
user_pref("vivipos.fec.settings.functionpanel.dir", "normal");
user_pref("vivipos.fec.settings.functionpanel.homePage", 1);
user_pref("vivipos.fec.settings.functionpanel.hspacing", 2);
user_pref("vivipos.fec.settings.functionpanel.maxpage", 3);
user_pref("vivipos.fec.settings.functionpanel.pageButtonfontsizeMap", "{\"1\":{\"1x1\":\"medium\",\"1x2\":\"medium\",\"1x3\":\"medium\",\"2x1\":\"medium\",\"2x2\":\"medium\",\"2x3\":\"medium\",\"3x1\":\"medium\",\"3x2\":\"medium\",\"3x3\":\"medium\",\"4x1\":\"medium\",\"4x2\":\"medium\",\"4x3\":\"medium\"}}");
user_pref("vivipos.fec.settings.functionpanel.pageButtonstyleMap", "{\"1\":{\"1x1\":\"function-button-color-3\",\"1x2\":\"function-button-color-3\",\"1x3\":\"function-button-color-3\",\"2x1\":\"function-button-color-3\",\"2x2\":\"function-button-color-3\",\"2x3\":\"function-button-color-3\",\"3x1\":\"function-button-color-3\",\"3x2\":\"function-button-color-3\",\"3x3\":\"function-button-color-3\",\"4x1\":\"function-button-color-3\",\"4x2\":\"function-button-color-3\",\"4x3\":\"function-button-color-3\"}}");
user_pref("vivipos.fec.settings.functionpanel.pageKeymapMap.1.1x2", "{\"row\":\"1\",\"column\":\"2\",\"name\":\"Surcharge\",\"label\":\"+5%\",\"desc\":\"This function registers a percentage surcharge. The parameter field can be used to program a preset surcharge. If no preset surcharge is programmed, the surcharge percentage is read from the input line.\",\"access\":\"acl_register_surcharge\",\"command\":\"addSurchargeByPercentage\",\"controller\":\"Cart\",\"data\":\"5\"}");
user_pref("vivipos.fec.settings.functionpanel.pageKeymapMap.1.1x3", "{\"row\":\"1\",\"column\":\"3\",\"name\":\"Percentage Discount\",\"label\":\"-5%\",\"desc\":\"This function registers a percentage-based discount. The parameter field can be used to program a preset percentage. If no preset percentage is programmed, the discount percentage is read from the input line.\",\"access\":\"acl_register_discount\",\"command\":\"addDiscountByPercentage\",\"controller\":\"Cart\",\"data\":\"5\"}");
user_pref("vivipos.fec.settings.functionpanel.pageKeymapMap.1.2x2", "{\"row\":\"2\",\"column\":\"2\",\"name\":\"PLUS\",\"label\":\"+5\",\"desc\":\"This function registers an addition. The parameter field can be used to program a preset addition amount. If no preset amount is programmed, the amount is read from the input line.\",\"access\":\"acl_register_addition\",\"command\":\"addSurchargeByNumber\",\"controller\":\"Cart\",\"data\":\"5\"}");
user_pref("vivipos.fec.settings.functionpanel.pageKeymapMap.1.2x3", "{\"row\":\"2\",\"column\":\"3\",\"name\":\"Reduction\",\"label\":\"-5\",\"desc\":\"This function registers a reduction. The parameter field can be used to program a preset reduction amount. If no preset amount is programmed, the discount amount is read from the input line.\",\"access\":\"acl_register_reduction\",\"command\":\"addDiscountByNumber\",\"controller\":\"Cart\",\"data\":\"5\"}");
user_pref("vivipos.fec.settings.functionpanel.pageLabelMap", "{}");
user_pref("vivipos.fec.settings.functionpanel.pageLayoutMap", "{\"1\":[\"1,1,1,1\",\"1,2,1,1\",\"1,3,1,1\",\"2,1,1,1\",\"2,2,1,1\",\"2,3,1,1\",\"3,1,1,1\",\"3,2,1,1\",\"3,3,1,1\",\"4,1,1,1\",\"4,2,1,1\",\"4,3,1,1\"]}");
user_pref("vivipos.fec.settings.functionpanel.restrictMode", "disabled");
user_pref("vivipos.fec.settings.functionpanel.rows", 2);
user_pref("vivipos.fec.settings.functionpanel.vspacing", 2);
user_pref("vivipos.fec.settings.functionpanel.wrap", "1");
user_pref("vivipos.fec.settings.login.allowquicklogin", true);
user_pref("vivipos.fec.settings.selectedDevices", "{\"receipt-1-enabled\":true,\"receipt-1-template\":\"receipt-sample-condensed\",\"receipt-1-port\":\"com1\",\"receipt-1-portspeed\":\" 9600\",\"receipt-1-devicemodel\":\"epsontm-t88iv\",\"receipt-1-encoding\":\"US-ASCII\",\"receipt-1-autoprint\":true,\"receipt-2-enabled\":false,\"receipt-2-template\":\"receipt-sample-condensed\",\"receipt-2-port\":\"com2\",\"receipt-2-portspeed\":\" 4800\",\"receipt-2-devicemodel\":\"escpos\",\"receipt-2-encoding\":\"UTF-8\",\"receipt-2-autoprint\":true,\"guestcheck-1-enabled\":false,\"guestcheck-1-template\":\"guestcheck-sample-condensed\",\"guestcheck-1-port\":\"com1\",\"guestcheck-1-portspeed\":\"2400\",\"guestcheck-1-devicemodel\":\"epsontm-t88iv\",\"guestcheck-1-encoding\":\"US-ASCII\",\"guestcheck-2-enabled\":false,\"guestcheck-2-template\":\"guestcheck-sample-condensed\",\"guestcheck-2-port\":\"com4\",\"guestcheck-2-portspeed\":\" 19200\",\"guestcheck-2-devicemodel\":\"epsontm-t88iv\",\"guestcheck-2-encoding\":\"ISO-8859-1\",\"vfd-1-enabled\":true,\"vfd-1-template\":\"vfd1\",\"vfd-1-port\":\"usb4\",\"vfd-1-portspeed\":\"2400\",\"vfd-1-devicemodel\":\"vfdfec\",\"vfd-1-encoding\":\"US-ASCII\",\"vfd-2-enabled\":false,\"vfd-2-template\":\"vfd1\",\"vfd-2-port\":\"com1\",\"vfd-2-portspeed\":\"2400\",\"vfd-2-devicemodel\":\"vfdfec\",\"vfd-2-encoding\":\"US-ASCII\",\"cashdrawer-1-enabled\":false,\"cashdrawer-1-type\":\"gpio\",\"cashdrawer-1-port\":\"com1\",\"cashdrawer-1-portspeed\":\"2400\",\"cashdrawer-1-devicemodel\":\"epsontm-t88iv\",\"cashdrawer-2-enabled\":false,\"cashdrawer-2-type\":\"gpio\",\"cashdrawer-2-port\":\"com1\",\"cashdrawer-2-portspeed\":\"2400\",\"cashdrawer-2-devicemodel\":\"epsontm-t88iv\"}");
user_pref("vivipos.fec.settings.sound.volume", 100);
user_pref("vivipos.fec.settings.sound.volume.0", 30);
user_pref("vivipos.fec.settings.sound.volume.1", true);
