[&INIT]
[&DWON]${'Transfer Table Notice'|center:21}[&DWOFF]
[&CR]
[&RESET]${'Printed:'|left:10} ${(new Date()).toLocaleFormat('%Y-%m-%d %H:%M:%S')}
[&CR]
${'Orignal:'|left:10} [&DWON] ${order.org_table_no} / ${order.org_table_name} [&DWOFF]
[&CR]
${'New:'|left:10} [&DWON] ${order.table_no} / ${order.table_name} [&DWOFF]
[&CR]
[&CR]
[&CR]
[&CR]
[&PC]
[&CR]
[&CR]
[&CR]
