#ifndef PORTCONTROLERROR_H_
#define PORTCONTROLERROR_H_

typedef enum
{
    PORTCONTROL_ERROR_SUCCESS        = 0,
    PORTCONTROL_ERROR_NOT_OPEN       = -1,
    PORTCONTROL_ERROR_IO_FAIL        = -2,
    PORTCONTROL_ERROR_NOT_AVAILABLE  = -3,
    PORTCONTROL_ERROR_DLE            = -4,
    PORTCONTROL_ERROR_NAK            = -5,
    PORTCONTROL_ERROR_NO_RESPONSE    = -6,
    PORTCONTROL_ERROR_RUNTIME        = -7
} PortControlError;

#endif /*PORTCONTROLERROR_H_*/
