#ifndef SMBIOS_VERSION_H
#define SMBIOS_VERSION_H
 // This is an automatically generated file, do not edit.
 // This file is generated by configure

#define LIBSMBIOS_RELEASE_VERSION "2.0.3"
 
#endif
