.\" matchbox-keyboard.1
.\" Copyright 2006  Moray Allan
.TH matchbox-keyboard 1 "Apr 15 2006" ""
.SH NAME
matchbox-keyboard \- on-screen keyboard
.SH SYNOPSIS
.B matchbox-keyboard
.\"
.SH DESCRIPTION
.B matchbox-keyboard
is an on-screen `virtual' or `software' keyboard, designed
for touch-screen devices running X.

Matchbox is a base environment for the X Window System running on non-desktop
embedded platforms such as handhelds, set-top boxes, kiosks and anything else
for which screen space, input mechanisms or system resources are limited.
.\"
.SH AUTHOR
.B matchbox-keyboard
was written by Matthew Allum <mallum@o-hand.com>.

