#include "nsISupports.idl"
[scriptable, uuid(AAF28D94-0FCC-46ba-9D79-04912B7325E2)]
interface nsIParallelPortControlUnix : nsISupports
{
    PRInt64 openPort(in AString portName, in AString portSettings);
    PRInt64 closePort(in AString portName);
    PRInt64 writePort (in AString portName, in ACString writeBuffer, in PRInt64 length);
    PRInt64 readPort (in AString portName, out ACString readBuffer, in PRInt64 length);
    PRInt32 statusPort (in AString portName);
    PRInt64 hdwrResetDevice (in AString portName);
};
