#!/bin/sh
APP_DIR=`dirname $0`/../..;
SDK_DIR="$APP_DIR/../../vivipos_sdk";

xgettext -o messages.po --omit-header --msgid-bugs-address=roundrock@vivicenter.com -Lpython -k_ $APP_DIR/content/controllers/*.js

#combine pot and po to properties and append default msgstr
msgcat messages.pot messages.po -o messages.properties.po

