#!/bin/sh

# include environment
. /etc/environment

# determine lang
CUR_LANG=`echo $LANG|sed "s/\.UTF-8//"|sed "s/_/-/"`

# vivipos extension dir
EXT_DIR=/data/profile/extensions
#EXT_DIR=~/.vivipos/8d8g43xw.default/extensions

#
# detect match langpack installed
#
LANGPACK_DIR="${EXT_DIR}/langpack-${CUR_LANG}@firich.com.tw"
if [ ! -d "$LANGPACK_DIR" ]; then

	CUR_LANG="en_US"
	LANGPACK_DIR="${EXT_DIR}/langpack-${CUR_LANG}@firich.com.tw"

fi

#
# check scripts.properties in /tmp
#
if [ -f "/tmp/scripts.properties" ]; then
	# include it.
	. "/tmp/scripts.properties"
else 

	#
	# check scripts.properties in langpack
	#
	if [ -f "$LANGPACK_DIR/chrome/locale/${CUR_LANG}/vivipos/scripts.properties" ]; then

		# add "" quote to properties.
		cat $LANGPACK_DIR/chrome/locale/${CUR_LANG}/vivipos/scripts.properties | awk -F"=" '{ print $1 "=\"" $2 "\"";  }' > /tmp/scripts.properties

		if [ -f "/tmp/scripts.properties" ]; then
			# include it.
			# . "$LANGPACK_DIR/chrome/locale/${CUR_LANG}/vivipos/scripts.properties" 
			. "/tmp/scripts.properties"
			# echo "$LANGPACK_DIR/chrome/locale/${CUR_LANG}/vivipos/scripts.properties"
		fi
	fi

fi

