#!/bin/sh
# This file is sourced by Xsession(5), not executed.

X11VNC=/usr/bin/x11vnc
PORT=5900

if [ -f /data/profile/x11vnc_setting.ini ]; then
    PORT=`cat /data/profile/x11vnc_setting.ini | grep port | sed s/port=//`
fi;

ARGS="-forever -shared -bg -rfbauth /data/profile/x11vnc_passwd -rfbport $PORT -logfile /var/log/x11vnc.log"

  if [ -x "$X11VNC" ]; then
	killall -9 x11vnc;
	$X11VNC $ARGS;
  fi

