#!/bin/sh
APP_DIR=`dirname $0`/../../;
SDK_DIR="$APP_DIR../../vivipos_sdk";

#flag=
#if [ -f messages.pot ]; then
#   flag=-j
#fi

xgettext -o messages.po --omit-header --msgid-bugs-address=irving.hsu@firich.com.tw -Lpython -k_ $APP_DIR/content/*.js $APP_DIR/content/controllers/*.js $SDK_DIR/chrome/content/bindings/*.xbl 

#combine pot and po to properties and append default msgstr
msgcat messages.pot messages.po -o messages.properties.po

