#!/bin/sh
#
# Start or stop the Advanced Power Management daemon.
#
# Written by Dirk Eddelbuettel <edd@debian.org>
# Greatly modified by Avery Pennarun <apenwarr@debian.org>
#
# I think this script is now free of bashisms.
# Please correct me if I'm wrong!

### BEGIN INIT INFO
# Provides:          apmd
# Required-Start:    $local_fs $remote_fs $syslog
# Required-Stop:     $local_fs $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Advanced Power Management (APM) daemon
### END INIT INFO

PATH=/bin:/usr/bin:/sbin:/usr/sbin
APMD_BIN="/usr/sbin/apmd"

[ ! -f /etc/default/rcS ] || . /etc/default/rcS
[ ! -f /etc/default/apmd ] || . /etc/default/apmd
test -f /lib/lsb/init-functions || exit 1
. /lib/lsb/init-functions

if [ "$VERBOSE" = "no" ]; then
        MODPROBE_OPTIONS="$MODPROBE_OPTIONS -Q"
        export MODPROBE_OPTIONS
fi

[ -s "${APMD_BIN}" ] || exit 0
modprobe -q apm >/dev/null 2>&1
apm_available || exit 0

case "${1}" in
("start")
    log_begin_msg "Starting Advanced Power Management daemon..."
    start-stop-daemon --start --quiet \
	    --exec "${APMD_BIN}" -- -P /etc/apm/apmd_proxy ${APMD}
    case $? in
    (0)
	log_end_msg 0
	exit 0
	;;
    (1)
	log_end_msg 0
	exit 0
	;;
    (*)
	log_end_msg 1
	exit 1
	;;
    esac
    ;;
("stop")
    log_begin_msg "Stopping Advanced Power Management daemon..."
    start-stop-daemon --stop --retry=1 --quiet --oknodo --exec "${APMD_BIN}"
    log_end_msg $?
    exit $?
    ;;
("restart" | "force-reload")
    "${0}" stop
    "${0}" start
    ;;
(*)
    log_success_msg "Usage: /etc/init.d/apmd {start|stop|restart|force-reload}" >&2
    exit 3
    ;;
esac
