#! /bin/sh
### BEGIN INIT INFO
# Provides:          reboot
# Required-Start:    umountroot $network
# Required-Stop:
# Should-Start:      lvm raid2
# Default-Start:     6
# Default-Stop:
# Short-Description: Execute the reboot command.
# Description:
### END INIT INFO

PATH=/usr/sbin:/usr/bin:/sbin:/bin

. /lib/lsb/init-functions

do_stop () {
	# Message should end with a newline since kFreeBSD may
	# print more stuff (see #323749)
	log_action_msg "Will now restart"
	reboot -d -f -i
}

case "$1" in
  start)
	# No-op
	;;
  restart|reload|force-reload)
	echo "Error: argument '$1' not supported" >&2
	exit 3
	;;
  stop)
	do_stop
	;;
  *)
	echo "Usage: $0 start|stop" >&2
	exit 3
	;;
esac
